/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ROBOT = 5;
  /** RegularExpression Id. */
  int VARS = 6;
  /** RegularExpression Id. */
  int PROCS = 7;
  /** RegularExpression Id. */
  int assign = 8;
  /** RegularExpression Id. */
  int goto1 = 9;
  /** RegularExpression Id. */
  int move = 10;
  /** RegularExpression Id. */
  int turn = 11;
  /** RegularExpression Id. */
  int face = 12;
  /** RegularExpression Id. */
  int put = 13;
  /** RegularExpression Id. */
  int pick = 14;
  /** RegularExpression Id. */
  int moveToThe = 15;
  /** RegularExpression Id. */
  int moveInDir = 16;
  /** RegularExpression Id. */
  int jumpToThe = 17;
  /** RegularExpression Id. */
  int jumpInDir = 18;
  /** RegularExpression Id. */
  int VARIABLEDEF = 19;
  /** RegularExpression Id. */
  int nop = 20;
  /** RegularExpression Id. */
  int BALLOONS = 21;
  /** RegularExpression Id. */
  int CHIPS = 22;
  /** RegularExpression Id. */
  int NUM = 23;
  /** RegularExpression Id. */
  int DIGIT = 24;
  /** RegularExpression Id. */
  int VARIABLE = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"ROBOT_R\"",
    "\"VARS\"",
    "\"PROCS\"",
    "\"assignTo\"",
    "\"goto\"",
    "\"move\"",
    "\"turn\"",
    "\"face\"",
    "\"put\"",
    "\"pick\"",
    "\"moveToThe\"",
    "\"moveInDir\"",
    "\"jumpToThe\"",
    "\"jumpInDir\"",
    "\"|\"",
    "\"nop\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUM>",
    "<DIGIT>",
    "<VARIABLE>",
    "\",\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
  };

}
